// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3rexP1OwmvDeUx84OuyplKcdwgZBlk8',
    appId: '1:148440258095:web:8f3119e4f069ff42add8da',
    messagingSenderId: '148440258095',
    projectId: 'chatapp-3707d',
    authDomain: 'chatapp-3707d.firebaseapp.com',
    storageBucket: 'chatapp-3707d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABP9OB4SVGlNGYVqaBg_BeNXE0bCktMYk',
    appId: '1:148440258095:android:f432dfe584c06532add8da',
    messagingSenderId: '148440258095',
    projectId: 'chatapp-3707d',
    storageBucket: 'chatapp-3707d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnGfWxTgurPltS3mOi4S64vAvkrV6zoA',
    appId: '1:148440258095:ios:d0f6a324c2bc6fe9add8da',
    messagingSenderId: '148440258095',
    projectId: 'chatapp-3707d',
    storageBucket: 'chatapp-3707d.appspot.com',
    iosClientId: '148440258095-ldodv1j97ljp3m7no1v5kscc6s15g7n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlnGfWxTgurPltS3mOi4S64vAvkrV6zoA',
    appId: '1:148440258095:ios:af793da001156a5fadd8da',
    messagingSenderId: '148440258095',
    projectId: 'chatapp-3707d',
    storageBucket: 'chatapp-3707d.appspot.com',
    iosClientId: '148440258095-i253ur745mei18e5dgq1udvjbogtik2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
